#!/usr/bin/env bash
# PreToolUse guard. Blocks edits to paths the agents should never touch.
# Reads the tool input from stdin as JSON; we use a tiny grep instead of
# pulling in jq to keep this dependency-free.

set -uo pipefail

input=$(cat)

# Extract the path argument from the tool input. Works for Write, Edit,
# str_replace, create_file — they all carry the path in a "path" or
# "file_path" field.
path=$(printf '%s' "$input" | grep -oE '"(path|file_path)"[[:space:]]*:[[:space:]]*"[^"]+"' | head -n1 | sed -E 's/.*"([^"]+)"$/\1/')

if [[ -z "$path" ]]; then
  exit 0   # Not an edit-style tool, let it through.
fi

block() {
  echo "Blocked: $path" >&2
  echo "Reason: $1" >&2
  echo "If this is intentional, ask the user to confirm before retrying." >&2
  exit 2
}

case "$path" in
  *.claude/*|*/.claude/*)
    block "Files under .claude/ are managed by the user, not agents."
    ;;
  *src/data/quran.json)
    block "quran.json is generated by scripts/fetch-quran.ts. Do not edit by hand."
    ;;
  *package-lock.json)
    block "Don't edit package-lock.json directly — let npm manage it."
    ;;
  *.env|*.env.*)
    block "Environment files are not in scope for this project."
    ;;
esac

exit 0
